### PR TITLE
Review for best practices

### PR DESCRIPTION
**Pull request by astroboyReloaded**
## Does my code stick to the following best practices?:
- [JavaScript best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).
- [DRY, KISS, and YAGNI](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/clean-code/lesson_DRY_KISS_YAGNI.md) rules.
- [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

### CODE REVIEW

**Comment by Muhammad0602** [comment]
## Hello @astroboyReloaded ,
 I'm Muhammad your reviewer for this PR. 😊
 
 Great work working on your project so far! :clap: There are some issues that you still need to work on to go to the next project but you are almost there!
 
DogSoCloseGIF


 ## Highlights

Great job setting up the correct linters :heavy_check_mark:
Meaningful commit messages :heavy_check_mark:
Github Flow was correctly used :heavy_check_mark: 

 
 ##  Required Changes :black_circle: 

 - [ ]  _Check the comments under the review._
 
 Cheers and Happy coding! :partying_face: :clap: :clap:

 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me  in your question so I can receive the notification.

**Comment by Muhammad0602** [comment]
## In Readme.md 
Please make a professional README file, right now it is empty. I am sure you know how to do it, as you have done it before.

**Comment by Muhammad0602** [comment]
<main>
        <article id="listContainer">
            <header class="list-header">
                <h1 class="list-title">Today's To Do</h1>
                <i id="restart-icon"></i>
            </header>
            <label class="input-label">
                <input
                    id="task-input"
                    type="text"
                    placeholder="Add to your list...">
                <i id="enter-btn"></i>
            </label>
            <ul id="taskList"></ul>
            <button
                id="clear"
                type="button">
                Clear all completed
            </button>
        </article>
    </main>

I think it would be better to add these using JavaScript as it was part of the requirements. It is important to be able to do this because in the next module when we study React, in our HTML files we will have only one container.

**Comment by Muhammad0602** [comment]
#restart-icon {
  display: block;
  margin: 12px 12px 12px auto;
  width: 18px;
  height: 18px;
  border: none;
  background:
    url('./images/icons/re-start.png')
    no-repeat;
  background-size: 18px;
  cursor: pointer;
}

.input-label {
  display: flex;
  width: 100%;
  height: fit-content;
  padding-block: 3px;
  border-bottom: 1px solid var(--gray);
}

#task-input {
  border: none;
  width: calc(100% - 6px);
  padding: 9px;
}

#task-input::placeholder {
  font-style: italic;
}

#task-input:focus {
  outline: none;
}

#enter-btn {
  display: block;
  margin: 12px 12px 12px auto;
  width: 18px;
  height: 18px;
  border: none;
  background:
    url('./images/icons/enter.png')
    no-repeat;
  background-size: 15px;
  cursor: pointer;
}

In CSS file your two buttons share almost the same code, so it would be better to use a class and add what they share and then specific features individually. It will make your code cleaner. 

Also, you are using the same code multiple times,  like `background: white` or `display: flex`. In this case you could create a class and add them to the elements that need it.

**Comment by astroboyReloaded** [comment]
- 🤣 Yes, you are right!
- Yes, I suppose it will be necessary to render everything with JS at some point.
- You are absolutely correct and I will take the time to put the repeated code in a single class.

Thank you!

**Comment by Muhammad0602** [comment]
You are welcome, if you have any questions feel free to ask here. Remember to tag my name so I get the notification.

**Comment by astroboyReloaded** [comment]
@Muhammad0602 
I made the changes you requested, except for rendering everything with js as the requirement only asks that we render the object with JS. Since the elements in the **HTML** file are not dynamic, there is no need to render them with JS and use that memory space.

**Comment by Muhammad0602** [comment]
Your project looks good. There is nothing else to say other than it's time to merge it.  Congratulations.
FlashingAnimatedGIF
###  Congratulations. 🎉👌

**Pull request merged**
